### ISSUE TITLE
5b OOM

### ISSUE THREAD

**Issue by zy0406** [TheDenk/cogvideox-controlnet#10]
Have you encountered the OOM issue with the 5b model ControlNet on the A100?

[rank0]:     out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 206.00 MiB. GPU 0 has a total capacity of 79.35 GiB of which 142.19 MiB is free. Process 256661 has 79.20 GiB memory in use. Of the allocated memory 77.25 GiB is allocated by PyTorch, and 30.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Steps:   0%|                                                                                                                                                                       | 0/10200 [00:12<?, ?it/s]
[rank0]:[W1127 19:37:03.772546111 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E1127 19:37:06.526107 140392017893184 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 397709) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main

**Comment by TheDenk** [comment]
Hey :)
No, I did not encounter with the OOM, especially on the A100. Do you try to train model or just inference?

**Comment by zy0406** [comment]
> Hey :) No, I did not encounter with the OOM, especially on the A100. Do you try to train model or just inference?

when i try to fintune cogvideox-5b-controlnet-hed-v1,
inference is ok

**Comment by zy0406** [comment]
> how many frames do you set? I trained with 41

I trained with 49 frames, now I solve it by changing  controlnet_transformer_num_layers to 6;
i will try 41
