### ISSUE TITLE
diffuer version

### ISSUE THREAD

**Issue by HaoZhang990127** [TheDenk/cogvideox-controlnet#12]
Hi,

Thank you for your nice work. When i use the new version of diffuser the following error comes,

/root/anaconda3/envs/control/lib/python3.11/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/root/anaconda3/envs/control/lib/python3.11/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/zhanghao/cogvideox-controlnet/training/train_controlnet.py", line 45, in <module>
    from diffusers.training_utils import (
ImportError: cannot import name 'clear_objs_and_retain_memory' from 'diffusers.training_utils' (/root/paddlejob/workspace/env_run/zhanghao/cogvideox-controlnet/training/diffusers/src/diffusers/training_utils.py)

could you tell me which diffuser version are you using? 

Thank you.

**Comment by TheDenk** [comment]
Hey, 
I've just checked diffusers==0.32.0 and it works well

**Comment by qianxingyucode** [comment]
> Hey, I've just checked diffusers==0.32.0 and it works well

@TheDenk 

Hi, I have tried the same version, but still have the same problem.
Could you please help me ?


bash finetune_single_rank.sh 
Traceback (most recent call last):
  File "/home/admin/workspace/Data/yuxing/cogvideox-controlnet-main/training/train_controlnet.py", line 45, in <module>
    from diffusers.training_utils import (
ImportError: cannot import name 'clear_objs_and_retain_memory' from 'diffusers.training_utils' (/usr/local/conda/lib/python3.10/site-packages/diffusers/training_utils.py)
E0306 06:07:23.869000 256051 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 256179) of binary: /usr/local/conda/bin/python
Traceback (most recent call last):
  File "/usr/local/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1190, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 808, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_controlnet.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-06_06:07:23
  host      : normandy-mlflow-debug-2w1glb-013857-bhfcl
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 256179)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

and pip list :

Package                  Version
------------------------ -----------
absl-py                  2.1.0
accelerate               1.4.0
aiofiles                 23.2.1
anaconda-anon-usage      0.4.4
annotated-types          0.7.0
anyio                    4.8.0
archspec                 0.2.3
asttokens                3.0.0
attrs                    25.1.0
boltons                  23.0.0
Brotli                   1.0.9
certifi                  2025.1.31
cffi                     1.16.0
charset-normalizer       2.0.4
click                    8.1.8
comm                     0.2.2
conda                    24.3.0
conda-content-trust      0.2.0
conda-libmamba-solver    24.1.0
conda-package-handling   2.2.0
conda_package_streaming  0.9.0
contourpy                1.3.1
controlnet-aux           0.0.9
cryptography             42.0.5
cycler                   0.12.1
debugpy                  1.8.12
decorator                5.2.1
decord                   0.6.0
denku                    0.0.51
**diffusers                0.32.0**
distro                   1.8.0
einops                   0.8.1
exceptiongroup           1.2.2
executing                2.1.0
fastapi                  0.115.8
ffmpy                    0.5.0
filelock                 3.13.1
flatbuffers              25.2.10
fonttools                4.56.0
fsspec                   2024.2.0
gradio                   5.19.0
gradio_client            1.7.2
h11                      0.14.0
hf_transfer              0.1.9
httpcore                 1.0.7
httpx                    0.28.1
huggingface-hub          0.29.1
idna                     3.4
imageio                  2.37.0
imageio-ffmpeg           0.6.0
importlib_metadata       8.6.1
ipykernel                6.29.5
ipython                  8.33.0
jax                      0.5.1
jaxlib                   0.5.1
jedi                     0.19.2
Jinja2                   3.1.3
jiter                    0.8.2
jsonpatch                1.33
jsonpointer              2.1
jupyter_client           8.6.3
jupyter_core             5.7.2
kiwisolver               1.4.8
lazy_loader              0.4
libmambapy               1.5.8
markdown-it-py           3.0.0
MarkupSafe               2.1.5
matplotlib               3.10.0
matplotlib-inline        0.1.7
mdurl                    0.1.2
mediapipe                0.10.21
menuinst                 2.0.2
ml_dtypes                0.5.1
moviepy                  2.1.2
mpmath                   1.3.0
nest_asyncio             1.6.0
networkx                 3.2.1
numpy                    1.26.0
nvidia-cublas-cu12       12.4.5.8
nvidia-cuda-cupti-cu12   12.4.127
nvidia-cuda-nvrtc-cu12   12.4.127
nvidia-cuda-runtime-cu12 12.4.127
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-cusparselt-cu12   0.6.2
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.4.127
openai                   1.64.0
opencv-contrib-python    4.11.0.86
opencv-python            4.11.0.86
opencv-python-headless   4.11.0.86
opt_einsum               3.4.0
orjson                   3.10.15
packaging                23.2
pandas                   2.2.3
parso                    0.8.4
peft                     0.14.0
pexpect                  4.9.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.3.1
platformdirs             3.10.0
pluggy                   1.0.0
proglog                  0.1.10
prompt_toolkit           3.0.50
protobuf                 4.25.6
psutil                   5.9.8
ptyprocess               0.7.0
pure_eval                0.2.3
pycosat                  0.6.6
pycparser                2.21
pydantic                 2.10.6
pydantic_core            2.27.2
pydub                    0.25.1
Pygments                 2.19.1
pyparsing                3.2.1
PySocks                  1.7.1
python-dateutil          2.9.0.post0
python-dotenv            1.0.1
python-multipart         0.0.20
pytz                     2025.1
PyYAML                   6.0.2
pyzmq                    26.2.0
regex                    2024.11.6
requests                 2.31.0
rich                     13.9.4
ruamel.yaml              0.17.21
ruamel.yaml.clib         0.2.6
ruff                     0.9.7
safehttpx                0.1.6
safetensors              0.5.3
scikit-image             0.24.0
scikit-video             1.1.11
scipy                    1.15.2
semantic-version         2.10.0
sentencepiece            0.2.0
setuptools               68.2.2
shellingham              1.5.4
six                      1.17.0
sniffio                  1.3.1
sounddevice              0.5.1
spaces                   0.32.0
spandrel                 0.4.1
stack_data               0.6.3
starlette                0.45.3
sympy                    1.13.1
tifffile                 2025.2.18
timm                     0.6.7
tokenizers               0.21.0
tomlkit                  0.13.2
torch                    2.6.0
torchaudio               2.2.2+cu121
torchvision              0.21.0
tornado                  6.4.2
tqdm                     4.67.1
traitlets                5.14.3
transformers             4.49.0
triton                   3.2.0
truststore               0.8.0
typer                    0.15.1
typing_extensions        4.12.2
tzdata                   2025.1
urllib3                  2.1.0
uvicorn                  0.34.0
wcwidth                  0.2.13
websockets               15.0
wheel                    0.41.2
zipp                     3.21.0
zstandard                0.19.0

**Comment by RookieCaoChao** [comment]
@qianxingyucode  
You can use the official operation of cogvideo, change `clear_objs_and_retain_memory([pipe])` to ```
del pipe
free_memory()
```

**Comment by RookieCChao** [comment]
@qianxingyucode 
You can use the official operation of cogvideo, change 
`clear_objs_and_retain_memory([pipe])`
 to 
```
del pipe
free_memory()
```
I think it might be the same effect.

**Comment by qianxingyucode** [comment]
@RookieCaoChao 
yes, I found that this function has been removed. And if use free memory(), it goes well.

Thank you for your help! 😄

**Comment by RookieCChao** [comment]
你好！感谢你来信，尽快给你回复。
