### ISSUE TITLE
cogvideo-5b  CUDA out of memory

### ISSUE THREAD

**Issue by linwenzhao1** [TheDenk/cogvideox-controlnet#16]
I used 2 A800 to fine-tune, but why is there still an CUDA out of memory error？
accelerate_config_machine_single.yaml:

compute_environment: LOCAL_MACHINE
main_process_port: 29501
debug: false
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
dynamo_backend: 'no'
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false

[rank3]:                              ~~~~~~~~~~~~~~~~~~^~~~~
[rank3]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 206.00 MiB. GPU 3 has a total capacity of 79.32 GiB of which 55.56 MiB is free. Including non-PyTorch memory, this process has 79.27 GiB memory in use. Of the allocated memory 76.93 GiB is allocated by PyTorch, and 22.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/robot/work/lwz/workspace/cogvideox-controlnet/training/train_controlnet.py", line 1170, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/robot/work/lwz/workspace/cogvideox-controlnet/training/train_controlnet.py", line 1076, in main
[rank0]:     model_output = transformer(
[rank0]:                    ^^^^^^^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/robot/work/lwz/workspace/cogvideox-controlnet/training/../cogvideo_transformer.py", line 64, in forward
[rank0]:     hidden_states, encoder_hidden_states = block(
[rank0]:                                            ^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/diffusers-0.32.0.dev0-py3.11.egg/diffusers/models/transformers/cogvideox_transformer_3d.py", line 132, in forward
[rank0]:     attn_hidden_states, attn_encoder_hidden_states = self.attn1(
[rank0]:                                                      ^^^^^^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/diffusers-0.32.0.dev0-py3.11.egg/diffusers/models/attention_processor.py", line 530, in forward
[rank0]:     return self.processor(
[rank0]:            ^^^^^^^^^^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/diffusers-0.32.0.dev0-py3.11.egg/diffusers/models/attention_processor.py", line 2293, in __call__
[rank0]:     query[:, :, text_seq_length:] = apply_rotary_emb(query[:, :, text_seq_length:], image_rotary_emb)
[rank0]:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/diffusers-0.32.0.dev0-py3.11.egg/diffusers/models/embeddings.py", line 816, in apply_rotary_emb
[rank0]:     out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
[rank0]:                              ~~~~~~~~~~~~~~~~~~^~~~~
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 206.00 MiB. GPU 0 has a total capacity of 79.32 GiB of which 151.56 MiB is free. Including non-PyTorch memory, this process has 79.17 GiB memory in use. Of the allocated memory 76.93 GiB is allocated by PyTorch, and 22.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank5]: Traceback (most recent call last):
[rank5]:   File "/home/robot/work/lwz/workspace/cogvideox-controlnet/training/train_controlnet.py", line 1170, in <module>
[rank5]:     main(args)
[rank5]:   File "/home/robot/work/lwz/workspace/cogvideox-controlnet/training/train_controlnet.py", line 1076, in main
[rank5]:     model_output = transformer(
[rank5]:                    ^^^^^^^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank5]:     return forward_call(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/robot/work/lwz/workspace/cogvideox-controlnet/training/../cogvideo_transformer.py", line 64, in forward
[rank5]:     hidden_states, encoder_hidden_states = block(
[rank5]:                                            ^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank5]:     return forward_call(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/diffusers-0.32.0.dev0-py3.11.egg/diffusers/models/transformers/cogvideox_transformer_3d.py", line 132, in forward
[rank5]:     attn_hidden_states, attn_encoder_hidden_states = self.attn1(
[rank5]:                                                      ^^^^^^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank5]:     return forward_call(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/diffusers-0.32.0.dev0-py3.11.egg/diffusers/models/attention_processor.py", line 530, in forward
[rank5]:     return self.processor(
[rank5]:            ^^^^^^^^^^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/diffusers-0.32.0.dev0-py3.11.egg/diffusers/models/attention_processor.py", line 2293, in __call__
[rank5]:     query[:, :, text_seq_length:] = apply_rotary_emb(query[:, :, text_seq_length:], image_rotary_emb)
[rank5]:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/conda_env/controlnet/lib/python3.11/site-packages/diffusers-0.32.0.dev0-py3.11.egg/diffusers/models/embeddings.py", line 816, in apply_rotary_emb
[rank5]:     out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
[rank5]:                              ~~~~~~~~~~~~~~~~~~^~~~~
[rank5]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 206.00 MiB. GPU 5 has a total capacity of 79.32 GiB of which 55.56 MiB is free. Including non-PyTorch memory, this process has 79.27 GiB memory in use. Of the allocated memory 76.93 GiB is allocated by PyTorch, and 22.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by TheDenk** [comment]
Hi,
How many frames?

**Comment by linwenzhao1** [comment]
> Hi, How many frames?

I changed it to 41 frames

**Comment by TheDenk** [comment]
5b model with 41 frames has to be trained without problems
