### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by AlphaNext** [TheDenk/cogvideox-controlnet#4]
Thanks for your amazing work! The test sample you provided can work normally. However, there is some errors when I input a video. 

My input video info are: 40 frames, height: 1280, width: 720, input as --video_path  param, and the shapes of hidden_states and controlnet_states are not match.

```
  2%|███▏                                                                                                                                                             | 1/50 [00:14<11:43, 14.37s/it]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cogvideox-controlnet-784f9c0/inference/cli_demo.py", line 201, in <module>
    generate_video(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)  File "/home/cogvideox-controlnet-784f9c0/inference/cli_demo.py", line 147, in generate_video
    video_generate = pipe(
    return func(*args, **kwargs)
  File "/home/cogvideox-controlnet-784f9c0/controlnet_pipeline.py", line 595, in __call__
    controlnet_states = self.controlnet(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/cogvideox-controlnet-784f9c0/cogvideo_controlnet.py", line 162, in forward
    hidden_states = torch.cat([hidden_states, controlnet_states], dim=2)
```
I print the shape of controlnet_states and hidden_states
* input controlnet_states shape is *torch.Size([2, 40, 3, 480, 720])*
* input hidden_states shape is *torch.Size([2, 13, 16, 60, 90])*
* processed controlnet_states shape is *torch.Size([2, 10, 48, 60, 90])*

Looking forward to your reply.

**Comment by TheDenk** [comment]
@AlphaNext hey :) Thanks for the message. This situation can occur when controlnet input frames count does not match with output frames count (For example 40 frames of controlnet on the input and 49 you set in the pipeline parameter (num_frames)). Probably I can fix it with frame duplication (for example first or last frame) or with frame interpolation to equalize the number of frames.

**Comment by TheDenk** [comment]
@AlphaNext I added duplication frames, now it should work.
